all:
  children:
    managed:
      hosts:
        server1:
          ansible_host: 172.31.33.128

        server2:
          ansible_host: 172.31.38.161

      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ./ansible-managed-key